# Generated by Django 2.2.3 on 2019-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('temp_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'booking_status',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_date', models.DateField(db_column='_date')),
            ],
            options={
                'managed': False,
                'db_table': 'scheduling',
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('slot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slot_time', models.CharField(max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'slots',
            },
        ),
    ]
