# Generated by Django 2.2.3 on 2019-09-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'booking_status',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('slot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slot_time', models.CharField(max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'slots',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('patcontact', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'patients',
            },
        ),
    ]
