# Generated by Django 2.2.3 on 2019-09-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='patcontact',
        ),
    ]
