# Generated by Django 2.2.3 on 2019-08-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scheduling',
        ),
    ]
