# Generated by Django 2.2.3 on 2019-09-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_patients_patcontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='slots',
            options={'managed': True},
        ),
    ]
