# Generated by Django 2.2.3 on 2019-09-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_delete_scheduling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scheduling',
        ),
    ]
