# Generated by Django 2.2.3 on 2019-09-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20190904_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='slots',
            options={'managed': False},
        ),
    ]
