# Generated by Django 2.2.3 on 2019-09-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20190904_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'managed': False},
        ),
    ]
