# Generated by Django 2.2.3 on 2019-09-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20190904_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slots',
            options={'managed': True},
        ),
    ]
