# Generated by Django 2.2.3 on 2019-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20190904_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='slot_day',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
