# Generated by Django 2.2.3 on 2019-09-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_slots_slot_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='slot_day',
        ),
    ]
